version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: ecommerce-db
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: ecommerce
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build:
      context: ./server
    ports:
      - "3000:3000"
    environment:
      DB_USER: root
      DB_PASSWORD: 123456
      DB_NAME: ecommerce
      DB_HOST: db
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
    ports:
      - "8080:80"  # Expondo o frontend na porta 8080
    depends_on:
      - api  # O frontend depende da API estar rodando

volumes:
  pgdata:
